name: Run Command on macOS

on:
  # 触发工作流的条件，可以是 push、pull_request 等
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # 指定运行环境为最新的 macOS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码到运行环境
        
      - name: Run macOS command
        run: |
          # 在这里编写你要执行的终端命令
          # 示例：打印当前目录、查看 macOS 版本
          sw_vers
          wget https://swscan.apple.com/content/catalogs/others/index-26seed-26-15-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog -o /tmp/catalog.xml
          # 查看文件内容
          cat /tmp/catalog.xml
          pip install -r requirements.txt
          #跑extract_urls.py脚本
          python3 extract_urls.py
          # python3 

          # 执行其他命令...
          softwareupdate --list-full-installers
          echo "Hello from macOS!"
          
      - name: Run another command
        run: |
          # 可以添加多个步骤执行不同的命令
          # 示例：创建文件并写入内容
          mkdir -p output
          echo "This is a test" > output/test.txt
          ls -la output/
